In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv('weatherHistory.csv')

In [4]:
df.head()

Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                   251.0          15.8263         0.0               1015.13   
1                   259.0          15.8263         0.0               1015.63   
2                   204.0          14.9569         0.0               1015.94   
3                   269.0          15.8263         0.0               1016.41   
4                   259.0          15.8263         0.0               1016.51   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.

In [19]:
df = df.set_index("Formatted Date")

In [8]:
df.head()

Summary Precip Type  Temperature (C)  \
Formatted Date                                                              
2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   

                               Apparent Temperature (C)  Humidity  \
Formatted Date                                                      
2006-04-01 00:00:00.000 +0200                  7.388889      0.89   
2006-04-01 01:00:00.000 +0200                  7.227778      0.86   
2006-04-01 02:00:00.000 +0200                  9.377778      0.89   
2006-04-01 03:00:00.000 +0200                  5.944444      0.83   
2006-04-01 04:00:00.000 +0200                  6.977778      0.83   

                               Wind Speed (km/h)  Wind Bearing (degrees)  \
Formatted Date                                                             
2006-04-01 00:00:00.000 +0200            14.1197                   251.0   
2006-04-01 01:00:00.000 +0200            14.2646                   259.0   
2006-04-01 02:00:00.000 +0200             3.9284                   204.0   
2006-04-01 03:00:00.000 +0200            14.1036                   269.0   
2006-04-01 04:00:00.000 +0200            11.0446                   259.0   

                               Visibility (km)  Loud Cover  \
Formatted Date                                               
2006-04-01 00:00:00.000 +0200          15.8263         0.0   
2006-04-01 01:00:00.000 +0200          15.8263         0.0   
2006-04-01 02:00:00.000 +0200          14.9569         0.0   
2006-04-01 03:00:00.000 +0200          15.8263         0.0   
2006-04-01 04:00:00.000 +0200          15.8263         0.0   

                               Pressure (millibars)  \
Formatted Date                                        
2006-04-01 00:00:00.000 +0200               1015.13   
2006-04-01 01:00:00.000 +0200               1015.63   
2006-04-01 02:00:00.000 +0200               1015.94   
2006-04-01 03:00:00.000 +0200               1016.41   
2006-04-01 04:00:00.000 +0200               1016.51   

                                                   Daily Summary  
Formatted Date                                                    
2006-04-01 00:00:00.000 +0200  Partly cloudy throughout the day.  
2006-04-01 01:00:00.000 +0200  Partly cloudy throughout the day.  
2006-04-01 02:00:00.000 +0200  Partly cloudy throughout the day.  
2006-04-01 03:00:00.000 +0200  Partly cloudy throughout the day.  
2006-04-01 04:00:00.000 +0200  Partly cloudy throughout the day.

In [20]:
df.index = pd.to_datetime(df.index)

In [10]:
df.head()

Summary Precip Type  Temperature (C)  \
Formatted Date                                                          
2006-04-01 00:00:00+02:00  Partly Cloudy        rain         9.472222   
2006-04-01 01:00:00+02:00  Partly Cloudy        rain         9.355556   
2006-04-01 02:00:00+02:00  Mostly Cloudy        rain         9.377778   
2006-04-01 03:00:00+02:00  Partly Cloudy        rain         8.288889   
2006-04-01 04:00:00+02:00  Mostly Cloudy        rain         8.755556   

                           Apparent Temperature (C)  Humidity  \
Formatted Date                                                  
2006-04-01 00:00:00+02:00                  7.388889      0.89   
2006-04-01 01:00:00+02:00                  7.227778      0.86   
2006-04-01 02:00:00+02:00                  9.377778      0.89   
2006-04-01 03:00:00+02:00                  5.944444      0.83   
2006-04-01 04:00:00+02:00                  6.977778      0.83   

                           Wind Speed (km/h)  Wind Bearing (degrees)  \
Formatted Date                                                         
2006-04-01 00:00:00+02:00            14.1197                   251.0   
2006-04-01 01:00:00+02:00            14.2646                   259.0   
2006-04-01 02:00:00+02:00             3.9284                   204.0   
2006-04-01 03:00:00+02:00            14.1036                   269.0   
2006-04-01 04:00:00+02:00            11.0446                   259.0   

                           Visibility (km)  Loud Cover  Pressure (millibars)  \
Formatted Date                                                                 
2006-04-01 00:00:00+02:00          15.8263         0.0               1015.13   
2006-04-01 01:00:00+02:00          15.8263         0.0               1015.63   
2006-04-01 02:00:00+02:00          14.9569         0.0               1015.94   
2006-04-01 03:00:00+02:00          15.8263         0.0               1016.41   
2006-04-01 04:00:00+02:00          15.8263         0.0               1016.51   

                                               Daily Summary  
Formatted Date                                                
2006-04-01 00:00:00+02:00  Partly cloudy throughout the day.  
2006-04-01 01:00:00+02:00  Partly cloudy throughout the day.  
2006-04-01 02:00:00+02:00  Partly cloudy throughout the day.  
2006-04-01 03:00:00+02:00  Partly cloudy throughout the day.  
2006-04-01 04:00:00+02:00  Partly cloudy throughout the day.

In [21]:
df = df[["Temperature (C)", "Humidity", "Pressure (millibars)", "Wind Speed (km/h)"]]

In [22]:
df.head()

Temperature (C)  Humidity  Pressure (millibars)  \
Formatted Date                                                               
2006-04-01 00:00:00+02:00         9.472222      0.89               1015.13   
2006-04-01 01:00:00+02:00         9.355556      0.86               1015.63   
2006-04-01 02:00:00+02:00         9.377778      0.89               1015.94   
2006-04-01 03:00:00+02:00         8.288889      0.83               1016.41   
2006-04-01 04:00:00+02:00         8.755556      0.83               1016.51   

                           Wind Speed (km/h)  
Formatted Date                                
2006-04-01 00:00:00+02:00            14.1197  
2006-04-01 01:00:00+02:00            14.2646  
2006-04-01 02:00:00+02:00             3.9284  
2006-04-01 03:00:00+02:00            14.1036  
2006-04-01 04:00:00+02:00            11.0446

In [41]:
df = df.iloc[:4018]

In [42]:
df

Temperature (C)  Humidity  Pressure (millibars)  \
Formatted Date                                                               
2006-04-01 00:00:00+02:00         9.472222      0.89               1015.13   
2006-04-01 01:00:00+02:00         9.355556      0.86               1015.63   
2006-04-01 02:00:00+02:00         9.377778      0.89               1015.94   
2006-04-01 03:00:00+02:00         8.288889      0.83               1016.41   
2006-04-01 04:00:00+02:00         8.755556      0.83               1016.51   
...                                    ...       ...                   ...   
2006-07-24 05:00:00+02:00        19.088889      0.96               1017.14   
2006-07-24 06:00:00+02:00        18.872222      1.00               1017.32   
2006-07-24 07:00:00+02:00        22.577778      0.85               1017.30   
2006-07-24 08:00:00+02:00        24.955556      0.78               1017.28   
2006-07-24 09:00:00+02:00        27.227778      0.65               1017.20   

                           Wind Speed (km/h)  
Formatted Date                                
2006-04-01 00:00:00+02:00            14.1197  
2006-04-01 01:00:00+02:00            14.2646  
2006-04-01 02:00:00+02:00             3.9284  
2006-04-01 03:00:00+02:00            14.1036  
2006-04-01 04:00:00+02:00            11.0446  
...                                      ...  
2006-07-24 05:00:00+02:00             3.2200  
2006-07-24 06:00:00+02:00             0.0000  
2006-07-24 07:00:00+02:00             0.0000  
2006-07-24 08:00:00+02:00             3.0107  
2006-07-24 09:00:00+02:00             2.9463  

[4018 rows x 4 columns]

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)

In [44]:
df_scaled

array([[0.49108384, 0.84931507, 0.97128614, 0.3880531 ],
       [0.48865215, 0.80821918, 0.97176455, 0.3920354 ],
       [0.48911533, 0.84931507, 0.97206116, 0.1079646 ],
       ...,
       [0.7642427 , 0.79452055, 0.97336242, 0.        ],
       [0.81380269, 0.69863014, 0.97334328, 0.08274336],
       [0.86116258, 0.52054795, 0.97326674, 0.08097345]])

In [45]:
np.isnan(np.sum(df_scaled))

False

In [46]:
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y, X_test, y_test = list(), list(), list(), list()
    for i in range(len(sequence)):
        #find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        #check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
        #gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        
        if i <= 3850:
            X.append(seq_x)
            y.append(seq_y)
        else:
            X_test.append(seq_x)
            y_test.append(seq_y)
    
    return np.array(X), np.array(y), np.array(X_test), np.array(y_test)

In [47]:
X, y, X_test, y_test = split_sequence(df_scaled, 120, 1)

In [48]:
print(X.shape)
print(y.shape)
print(X_test.shape)
print(y_test.shape)

(3851, 120, 4)
(3851, 1, 4)
(47, 120, 4)
(47, 1, 4)


In [51]:
n_features, n_epochs, n_neurons = df.columns.size, 10, 50

In [52]:
X = X.reshape((X.shape[0], X.shape[1], n_features))
y = y.reshape((y.shape[0], y.shape[1], n_features))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], n_features))
y_test = y_test.reshape((y_test.shape[0], y_test.shape[1], n_features))

In [53]:
print(X.shape)
print(y.shape)
print(X_test.shape)
print(y_test.shape)

(3851, 120, 4)
(3851, 1, 4)
(47, 120, 4)
(47, 1, 4)


In [49]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import RepeatVector
from tensorflow.keras.layers import TimeDistributed

In [54]:
n_steps_in, n_steps_out = 120, 1

In [107]:
model = Sequential()
model.add(LSTM(n_neurons, activation='tanh', input_shape = (n_steps_in, n_features)))
model.add(RepeatVector(n_steps_out))
model.add(LSTM(n_neurons, activation='tanh', return_sequences=True))
model.add(TimeDistributed(Dense(n_features)))
model.compile(optimizer="adam", loss = "mse")
model.fit(X[:1],y[:1], epochs=n_epochs, verbose=1)

C:\Users\Admin\anaconda3new\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - loss: 0.4786
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.4607
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.4431
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.4254
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 0.4074
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step - loss: 0.3888
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - loss: 0.3692
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - loss: 0.3485
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 0.3264
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.3026


In [56]:
model.save('model_1.h5')

In [57]:
model = tf.keras.models.load_model('model_1.h5')

TypeError: Could not locate function 'mse'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`. Full object config: {'module': 'keras.metrics', 'class_name': 'function', 'config': 'mse', 'registered_name': 'mse'}

In [58]:
model = tf.keras.models.load_model("model_1.h5", compile=False)

In [59]:
model.compile(optimizer="adam", loss=tf.keras.losses.MeanSquaredError(), metrics=["accuracy"])

In [108]:
y_real = scaler.inverse_transform(y_test[:,0])

In [109]:
y_real[:,0]

array([31.01111111, 32.28888889, 32.85      , 32.79444444, 33.88888889,
       33.88888889, 33.86111111, 32.72777778, 31.00555556, 25.46666667,
       22.93333333, 21.78333333, 21.27777778, 20.66666667, 21.13333333,
       20.76666667, 20.53333333, 20.97777778, 19.9       , 20.95555556,
       21.07222222, 21.44444444, 24.00555556, 26.25      , 26.54444444,
       28.05555556, 29.18888889, 31.23888889, 32.26666667, 31.03888889,
       30.08333333, 28.81111111, 27.18333333, 24.47222222, 23.96111111,
       22.80555556, 21.92777778, 21.11666667, 20.58333333, 19.80555556,
       19.91111111, 19.88888889, 19.08888889, 18.87222222, 22.57777778,
       24.95555556, 27.22777778])

In [62]:
df.tail(47)

Temperature (C)  Humidity  Pressure (millibars)  \
Formatted Date                                                               
2006-07-22 11:00:00+02:00        31.011111      0.45               1018.02   
2006-07-22 12:00:00+02:00        32.288889      0.41               1017.64   
2006-07-22 13:00:00+02:00        32.850000      0.34               1017.15   
2006-07-22 14:00:00+02:00        32.794444      0.33               1016.77   
2006-07-22 15:00:00+02:00        33.888889      0.35               1016.14   
2006-07-22 16:00:00+02:00        33.888889      0.30               1014.97   
2006-07-22 17:00:00+02:00        33.861111      0.35               1015.50   
2006-07-22 18:00:00+02:00        32.727778      0.37               1014.48   
2006-07-22 19:00:00+02:00        31.005556      0.44               1014.80   
2006-07-22 20:00:00+02:00        25.466667      0.61               1016.26   
2006-07-22 21:00:00+02:00        22.933333      0.73               1018.12   
2006-07-22 22:00:00+02:00        21.783333      0.76               1017.80   
2006-07-22 23:00:00+02:00        21.277778      0.79               1017.17   
2006-07-23 00:00:00+02:00        20.666667      0.83               1016.70   
2006-07-23 01:00:00+02:00        21.133333      0.79               1016.47   
2006-07-23 02:00:00+02:00        20.766667      0.93               1017.04   
2006-07-23 03:00:00+02:00        20.533333      0.89               1017.50   
2006-07-23 04:00:00+02:00        20.977778      0.81               1016.88   
2006-07-23 05:00:00+02:00        19.900000      0.88               1016.28   
2006-07-23 06:00:00+02:00        20.955556      0.81               1016.05   
2006-07-23 07:00:00+02:00        21.072222      0.87               1015.95   
2006-07-23 08:00:00+02:00        21.444444      0.85               1016.58   
2006-07-23 09:00:00+02:00        24.005556      0.78               1016.98   
2006-07-23 10:00:00+02:00        26.250000      0.64               1017.08   
2006-07-23 11:00:00+02:00        26.544444      0.63               1017.49   
2006-07-23 12:00:00+02:00        28.055556      0.62               1017.25   
2006-07-23 13:00:00+02:00        29.188889      0.58               1017.06   
2006-07-23 14:00:00+02:00        31.238889      0.49               1016.77   
2006-07-23 15:00:00+02:00        32.266667      0.45               1016.14   
2006-07-23 16:00:00+02:00        31.038889      0.48               1015.60   
2006-07-23 17:00:00+02:00        30.083333      0.47               1015.83   
2006-07-23 18:00:00+02:00        28.811111      0.60               1015.78   
2006-07-23 19:00:00+02:00        27.183333      0.73               1015.70   
2006-07-23 20:00:00+02:00        24.472222      0.77               1015.94   
2006-07-23 21:00:00+02:00        23.961111      0.89               1016.19   
2006-07-23 22:00:00+02:00        22.805556      0.92               1016.90   
2006-07-23 23:00:00+02:00        21.927778      0.91               1016.97   
2006-07-24 00:00:00+02:00        21.116667      0.92               1017.20   
2006-07-24 01:00:00+02:00        20.583333      0.90               1017.12   
2006-07-24 02:00:00+02:00        19.805556      0.92               1018.17   
2006-07-24 03:00:00+02:00        19.911111      0.97               1016.92   
2006-07-24 04:00:00+02:00        19.888889      0.93               1016.73   
2006-07-24 05:00:00+02:00        19.088889      0.96               1017.14   
2006-07-24 06:00:00+02:00        18.872222      1.00               1017.32   
2006-07-24 07:00:00+02:00        22.577778      0.85               1017.30   
2006-07-24 08:00:00+02:00        24.955556      0.78               1017.28   
2006-07-24 09:00:00+02:00        27.227778      0.65               1017.20   

                           Wind Speed (km/h)  
Formatted Date                                
2006-07-22 11:00:00+02:00             7.3416  
2006-07-22 12:00:00+02:00             7.5026  
2006-07-22 13:00

In [110]:
y_predict = []
for i in range(len(X_test)):
    x_pred = X_test[i].reshape((1, X_test[i].shape[0], n_features))
    y_pred = model.predict(x_pred)
    y_pred_itrans = scaler.inverse_transform(y_pred[0])
    y_predict.append(y_pred_itrans)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 585ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━

In [111]:
y_predict

[array([[ -7.306794 ,   0.3993867, 222.75223  ,   1.2307987]],
       dtype=float32),
 array([[ -7.5068555 ,   0.39855617, 220.32257   ,   1.2026877 ]],
       dtype=float32),
 array([[ -7.712835  ,   0.39768562, 217.65097   ,   1.1756785 ]],
       dtype=float32),
 array([[ -7.928561  ,   0.39683977, 215.07555   ,   1.1559877 ]],
       dtype=float32),
 array([[ -8.148212 ,   0.3955406, 212.00186  ,   1.1317174]],
       dtype=float32),
 array([[ -8.299767  ,   0.39494777, 209.70854   ,   1.1292418 ]],
       dtype=float32),
 array([[ -8.465428  ,   0.39394572, 207.14606   ,   1.1074808 ]],
       dtype=float32),
 array([[ -8.569755  ,   0.39348364, 205.48582   ,   1.1146569 ]],
       dtype=float32),
 array([[ -8.632654  ,   0.39324015, 204.68501   ,   1.1235962 ]],
       dtype=float32),
 array([[ -8.680639  ,   0.39218834, 203.39009   ,   1.1080767 ]],
       dtype=float32),
 array([[ -8.394916  ,   0.39694703, 211.52629   ,   1.322697  ]],
       dtype=float32),
 array([[ -8.08555

In [112]:
Temp, Humidty, Pressure, WindSpd = [],[],[],[]
for i in y_predict:
    Temp.append(i[0][0])
    Humidty.append(i[0][1])
    Pressure.append(i[0][2])
    WindSpd.append(i[0][3])

In [69]:
from sklearn.metrics import mean_squared_error, mean_squared_log_error, mean_absolute_error
from math import sqrt

In [113]:
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred)/y_true)) * 100

In [114]:
Temp_mae = mean_absolute_error(Temp, y_real[:,0])

Temp_rase = sqrt(mean_squared_error(Temp, y_real[:,0]))

Temp_mape = mean_absolute_percentage_error(Temp, y_real[:,0])

Humidity_mae = mean_absolute_error(Humidty, y_real[:,1])

Humidity_rase = sqrt(mean_squared_error(Humidty, y_real[:,1]))

Humidity_mape = mean_absolute_percentage_error(Humidty, y_real[:,1])

Pressure_mae = mean_absolute_error(Pressure, y_real[:,2])

Pressure_rase = sqrt(mean_squared_error(Pressure, y_real[:,2]))

Pressure_mape = mean_absolute_percentage_error(Pressure, y_real[:,2])

WindSpd_mae = mean_absolute_error(WindSpd, y_real[:,3])

WindSpd_rase = sqrt(mean_squared_error(WindSpd, y_real[:,3]))

WindSpd_mape = mean_absolute_percentage_error(WindSpd, y_real[:,3])

In [115]:
results = pd.DataFrame({

    "Variable": ["Temp", "Humidity", "Pressure", "WindSpd"],

    "MAE":[Temp_mae, Humidity_mae, Pressure_mae, WindSpd_mae],

    "RMSE": [Temp_rase, Humidity_rase, Pressure_rase, WindSpd_rase],

    "MAPE": [Temp_mape, Humidity_mape, Pressure_mape, WindSpd_mape]

})


result_df = results.sort_values(by = "MAE", ascending = False)

result_df = result_df.set_index('Variable')

result_df

MAE        RMSE        MAPE
Variable                                    
Pressure  793.634606  793.683474  356.589222
Temp       32.875727   33.296053  440.755984
WindSpd     5.255824    7.873818  411.816808
Humidity    0.310019    0.361495   77.139445

In [88]:
Temp_mae

36.57965890915963

In [118]:
y_pred

array([[[0.15586725, 0.18180355, 0.22151472, 0.03536177]]], dtype=float32)

In [119]:
scaler.inverse_transform(y_pred[0])

array([[ -6.610725  ,   0.40271658, 231.51389   ,   1.2866732 ]],
      dtype=float32)

In [91]:
y

array([[[0.43168133, 0.79452055, 0.96850183, 0.34955752]],

       [[0.4201019 , 0.83561644, 0.96899937, 0.35442478]],

       [[0.46746179, 0.83561644, 0.97149664, 0.01902655]],

       ...,

       [[0.80662344, 0.5890411 , 0.97425225, 0.16681416]],

       [[0.86347846, 0.50684932, 0.97408003, 0.21061947]],

       [[0.92044928, 0.32876712, 0.97398435, 0.12876106]]])

In [93]:
scaler.inverse_transform(y[0])

array([[6.62222222e+00, 8.50000000e-01, 1.01222000e+03, 1.27190000e+01]])

In [98]:
X[0][0]

array([0.49108384, 0.84931507, 0.97128614, 0.3880531 ])

In [100]:
scaler.inverse_transform([X[0][0]])

array([[9.47222222e+00, 8.90000000e-01, 1.01513000e+03, 1.41197000e+01]])

In [105]:
X

array([[[0.49108384, 0.84931507, 0.97128614, 0.3880531 ],
        [0.48865215, 0.80821918, 0.97176455, 0.3920354 ],
        [0.48911533, 0.84931507, 0.97206116, 0.1079646 ],
        ...,
        [0.45819824, 0.75342466, 0.9676407 , 0.27477876],
        [0.44603983, 0.76712329, 0.96791817, 0.37610619],
        [0.44661881, 0.78082192, 0.96826263, 0.31725664]],

       [[0.48865215, 0.80821918, 0.97176455, 0.3920354 ],
        [0.48911533, 0.84931507, 0.97206116, 0.1079646 ],
        [0.46641964, 0.76712329, 0.97251086, 0.38761062],
        ...,
        [0.44603983, 0.76712329, 0.96791817, 0.37610619],
        [0.44661881, 0.78082192, 0.96826263, 0.31725664],
        [0.43168133, 0.79452055, 0.96850183, 0.34955752]],

       [[0.48911533, 0.84931507, 0.97206116, 0.1079646 ],
        [0.46641964, 0.76712329, 0.97251086, 0.38761062],
        [0.47614636, 0.76712329, 0.97260654, 0.30353982],
        ...,
        [0.44661881, 0.78082192, 0.96826263, 0.31725664],
        [0.43168133, 0.794520

In [106]:
y

array([[[0.43168133, 0.79452055, 0.96850183, 0.34955752]],

       [[0.4201019 , 0.83561644, 0.96899937, 0.35442478]],

       [[0.46746179, 0.83561644, 0.97149664, 0.01902655]],

       ...,

       [[0.80662344, 0.5890411 , 0.97425225, 0.16681416]],

       [[0.86347846, 0.50684932, 0.97408003, 0.21061947]],

       [[0.92044928, 0.32876712, 0.97398435, 0.12876106]]])